#!/usr/bin/env bash
# =============================================================================
# openclash-rt  procd 垫片单元测试
# -----------------------------------------------------------------------------
# 回放上游 OpenClash /etc/init.d/openclash 中**逐字复制**的 14 处 procd 调用，
# 校验垫片生成的 systemd 单元、包装脚本、注册表与生命周期语义。
# 可在无 systemd 的环境（Windows/MSYS、CI 容器）运行。
#
# 用法： bash tests/test_procd_shim.sh
# =============================================================================
set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
PROCD_SH="$ROOT/runtime/procd/procd.sh"
MOCK_BIN="$HERE/mock/bin"

# ⚠️ 不要用 ${TMPDIR}：Windows/MSYS 沙箱下它可能被设为 Windows 盘符路径，
# 会被安全策略判为 "embedded drive prefix" 而拒绝 rm。硬编码 /tmp 最稳。
WORK="/tmp/ocrt-test.$$"
rm -rf "$WORK" 2>/dev/null || true
mkdir -p "$WORK"
export OPENCLASH_RT_ROOT="$WORK/rt"
export OPENCLASH_RT_UNIT_DIR="$WORK/units-systemd"
export MOCK_SYSTEMD_STATE="$WORK/systemd-state"
export PATH="$MOCK_BIN:$PATH"
export OPENCLASH_RT_LOG="$WORK/rt.log"

PASS=0
FAIL=0
CURRENT=""

it() { CURRENT="$1"; printf '\n\033[1m── %s\033[0m\n' "$1"; }

ok() { PASS=$((PASS + 1)); printf '  \033[32mPASS\033[0m  %s\n' "$1"; }
no() { FAIL=$((FAIL + 1)); printf '  \033[31mFAIL\033[0m  %s\n' "$1"; }

assert_eq() {
	local want="$1" got="$2" what="$3"
	if [ "$want" = "$got" ]; then ok "$what"; else
		no "$what"
		printf '        want: %s\n        got : %s\n' "$(printf '%q' "$want")" "$(printf '%q' "$got")"
	fi
}

assert_file_eq() {
	local f="$1" want="$2" what="$3"
	if [ ! -f "$f" ]; then no "$what (文件不存在: $f)"; return; fi
	local got; got="$(cat "$f")"
	assert_eq "$want" "$got" "$what"
}

assert_grep() {
	local pat="$1" f="$2" what="$3"
	if [ ! -f "$f" ]; then no "$what (文件不存在: $f)"; return; fi
	if grep -qF -- "$pat" "$f"; then ok "$what"; else
		no "$what"
		printf '        未在 %s 中找到: %s\n' "$(basename "$f")" "$pat"
	fi
}

assert_no_grep() {
	local pat="$1" f="$2" what="$3"
	if [ -f "$f" ] && grep -qF -- "$pat" "$f"; then
		no "$what"; printf '        意外命中: %s\n' "$pat"
	else ok "$what"; fi
}

cleanup() {
	# 回收 mock systemctl 真实 spawn 出来的 sleep，避免进程泄漏
	local f p
	for f in "$MOCK_SYSTEMD_STATE"/*.pid; do
		[ -f "$f" ] || continue
		p="$(cat "$f" 2>/dev/null)"
		[ -n "$p" ] && kill -TERM "$p" 2>/dev/null
	done
	rm -rf "$WORK" 2>/dev/null || true
}
trap cleanup EXIT

mkdir -p "$OPENCLASH_RT_ROOT" "$OPENCLASH_RT_UNIT_DIR" "$MOCK_SYSTEMD_STATE"

# shellcheck source=/dev/null
. "$PROCD_SH"

# =============================================================================
it "1. 参数引号转义 _oc_sq"
# =============================================================================
assert_eq "'abc'" "$(_oc_sq 'abc')" "普通字符串"
assert_eq "'a'\\''b'" "$(_oc_sq "a'b")" "内嵌单引号"
assert_eq "''" "$(_oc_sq '')" "空字符串"
assert_eq "'a b  c'" "$(_oc_sq 'a b  c')" "含空格"

# =============================================================================
it "2. 回放上游 start_service 的 procd 调用序列"
# =============================================================================
# ↓↓↓ 以下调用顺序与参数与上游 /etc/init.d/openclash 完全一致 ↓↓↓
procd_open_service "openclash" "/etc/init.d/openclash"

# --- start_run_core() (openclash:814-826) ---
procd_open_instance "openclash"
procd_set_param env SAFE_PATHS=/usr/share/openclash:/etc/ssl
procd_append_param env CLASH_AGE_SECRET_KEY="my secret key"
procd_append_param env OIX_TOKEN=""
procd_append_param env OIX_PARAMS=""
procd_set_param command /bin/sh -c "exec /etc/openclash/clash -d /etc/openclash -f \"/etc/openclash/cfg.yaml\" >> /tmp/openclash.log 2>&1"
procd_set_param user "root"
procd_set_param group "nogroup"
procd_set_param limits nproc="unlimited" as="unlimited" memlock="unlimited" nofile="1000000 1000000"
procd_set_param respawn 300 5 3
procd_set_param stderr 1
procd_set_param no_new_privs 1
procd_close_instance

# --- start_watchdog() (openclash:3786-3788) ---
procd_open_instance "openclash-watchdog"
procd_set_param command "/usr/share/openclash/openclash_watchdog.sh"
procd_close_instance

procd_close_service set
# ↑↑↑ 回放结束 ↑↑↑

CORE_UNIT="$OPENCLASH_RT_UNIT_DIR/openclash-rt-openclash.service"
WD_UNIT="$OPENCLASH_RT_UNIT_DIR/openclash-rt-openclash-watchdog.service"
CORE_WRAP="$OPENCLASH_RT_ROOT/units/openclash.sh"
WD_WRAP="$OPENCLASH_RT_ROOT/units/openclash-watchdog.sh"

if [ -f "$CORE_UNIT" ]; then ok "生成 core 单元文件"; else no "生成 core 单元文件"; fi
if [ -f "$WD_UNIT" ]; then ok "生成 watchdog 单元文件"; else no "生成 watchdog 单元文件"; fi

# =============================================================================
it "3. 包装脚本（argv 必须逐字还原）"
# =============================================================================
assert_file_eq "$CORE_WRAP" "#!/bin/sh
# generated by openclash-rt - do not edit
exec '/bin/sh' '-c' 'exec /etc/openclash/clash -d /etc/openclash -f \"/etc/openclash/cfg.yaml\" >> /tmp/openclash.log 2>&1'" \
	"core 包装脚本 argv 逐字还原"

assert_file_eq "$WD_WRAP" "#!/bin/sh
# generated by openclash-rt - do not edit
exec '/usr/share/openclash/openclash_watchdog.sh'" \
	"watchdog 包装脚本 argv 逐字还原"

if [ -x "$CORE_WRAP" ]; then ok "包装脚本可执行"; else no "包装脚本可执行"; fi

# =============================================================================
it "4. 单元文件关键字段"
# =============================================================================
assert_grep "ExecStart=/bin/sh $CORE_WRAP" "$CORE_UNIT" "ExecStart 指向包装脚本"
assert_grep "Type=simple"             "$CORE_UNIT" "Type=simple"
assert_grep "Restart=always"          "$CORE_UNIT" "procd respawn -> Restart=always"
assert_grep "RestartSec=5"            "$CORE_UNIT" "respawn timeout -> RestartSec=5"
assert_grep "StartLimitIntervalSec=300" "$CORE_UNIT" "respawn threshold -> StartLimitIntervalSec=300"
assert_grep "StartLimitBurst=3"       "$CORE_UNIT" "respawn retry -> StartLimitBurst=3"
assert_grep "User=root"               "$CORE_UNIT" "user"
assert_grep "Group=nogroup"           "$CORE_UNIT" "group"
assert_grep "NoNewPrivileges=true"    "$CORE_UNIT" "no_new_privs"
assert_grep "StandardError=journal"   "$CORE_UNIT" "stderr=1"

# =============================================================================
it "5. limits / env 映射"
# =============================================================================
assert_grep "LimitNPROC=infinity"     "$CORE_UNIT" "nproc=unlimited -> infinity"
assert_grep "LimitAS=infinity"        "$CORE_UNIT" "as=unlimited -> infinity"
assert_grep "LimitMEMLOCK=infinity"   "$CORE_UNIT" "memlock=unlimited -> infinity"
assert_grep "LimitNOFILE=1000000"     "$CORE_UNIT" "nofile=\"1000000 1000000\" 取 soft"
assert_grep "Environment=SAFE_PATHS=/usr/share/openclash:/etc/ssl" "$CORE_UNIT" "env 无空格不加引号"
assert_grep 'Environment="CLASH_AGE_SECRET_KEY=my secret key"'    "$CORE_UNIT" "env 含空格自动加引号"
assert_grep "Environment=OIX_TOKEN=" "$CORE_UNIT" "env 空值保留"

# =============================================================================
it "6. service -> instances 注册表"
# =============================================================================
REG="$OPENCLASH_RT_ROOT/services/openclash.instances"
if [ -f "$REG" ]; then ok "注册表已写入"; else no "注册表已写入"; fi
assert_file_eq "$REG" "openclash
openclash-watchdog" "注册表内容含两个 instance"

# =============================================================================
it "7. procd_running 语义"
# =============================================================================
if procd_running "openclash"; then ok "启动后 procd_running <svc> = true"; else no "启动后 procd_running <svc> = true"; fi
if procd_running "openclash" "openclash"; then ok "procd_running <svc> <inst> = true"; else no "procd_running <svc> <inst> = true"; fi
if procd_running "openclash" "openclash-watchdog"; then ok "watchdog instance running"; else no "watchdog instance running"; fi
if procd_running "openclash" "no-such-instance"; then no "未知 instance 应为 false"; else ok "未知 instance 为 false"; fi
if procd_running "no-such-service"; then no "未知 service 应为 false"; else ok "未知 service 为 false"; fi

# =============================================================================
it "8. procd_send_signal"
# =============================================================================
if procd_send_signal "openclash" "openclash-watchdog" CONT; then ok "发送 CONT 成功"; else no "发送 CONT 成功"; fi
if procd_send_signal "openclash" "openclash-watchdog" STOP; then ok "发送 STOP 成功"; else no "发送 STOP 成功"; fi
if procd_send_signal "openclash" "*" TERM; then ok "广播 TERM 成功"; else no "广播 TERM 成功"; fi

# =============================================================================
it "9. procd_kill 语义（上游 stop_service 依赖）"
# =============================================================================
procd_kill "openclash"
if procd_running "openclash"; then no "kill 后 procd_running = false"; else ok "kill 后 procd_running = false"; fi
if [ -s "$REG" ]; then no "kill 后注册表被清空"; else ok "kill 后注册表被清空"; fi
if [ -f "$MOCK_SYSTEMD_STATE/openclash-rt-openclash.active" ]; then
	no "core 单元已停止（上游 procd_running 轮询依赖此状态）"
else ok "core 单元已停止"; fi
if [ -f "$MOCK_SYSTEMD_STATE/openclash-rt-openclash-watchdog.active" ]; then
	no "watchdog 单元已停止"
else ok "watchdog 单元已停止"; fi

# =============================================================================
it "10. 可重复启动（start -> stop -> start）"
# =============================================================================
procd_open_service "openclash" "/etc/init.d/openclash"
procd_open_instance "openclash"
procd_set_param command /bin/sh -c "exec /etc/openclash/clash -d /etc/openclash"
procd_close_instance
procd_close_service set
if procd_running "openclash" "openclash"; then ok "二次启动成功"; else no "二次启动成功"; fi
procd_kill "openclash"

# =============================================================================
it "11. 异常路径"
# =============================================================================
procd_open_instance "orphan"
procd_set_param command /bin/true
procd_close_instance
ok "未 open_service 时 close_instance 不崩溃"

procd_open_service "empty-svc" "/etc/init.d/empty"
procd_close_service set
ok "无 instance 的 close_service 不崩溃"

assert_grep "open_service name=openclash" "$OPENCLASH_RT_LOG" "诊断日志记录 open_service"

# =============================================================================
printf '\n\033[1m════════════════════════════════════════\033[0m\n'
printf '  PASS: \033[32m%d\033[0m    FAIL: \033[31m%d\033[0m\n' "$PASS" "$FAIL"
printf '\033[1m════════════════════════════════════════\033[0m\n'
[ "$FAIL" -eq 0 ] || exit 1
