#!/usr/bin/env bash
# =============================================================================
# openclash-rt  dnsmasq 适配器（UCI → /etc/dnsmasq.d/）
# -----------------------------------------------------------------------------
# 上游 OpenClash 通过 UCI 修改 dnsmasq 的转发表，因为它假定目标系统是 OpenWrt：
#
#   uci -q set  dhcp.@dnsmasq[0].server=127.0.0.1#7874   # DNS 转给 OpenClash
#   uci -q set  dhcp.@dnsmasq[0].noresolv=1
#   uci -q set  dhcp.@dnsmasq[0].resolvfile=...
#   uci -q set  dhcp.@dnsmasq[0].localuse=1
#   uci -q set  dhcp.@dnsmasq[0].cachesize=0
#   uci -q set  dhcp.@dnsmasq[0].filter_aaaa=0
#   uci -q commit dhcp
#   /etc/init.d/dnsmasq restart
#
# Debian 的 dnsmasq **完全不读 UCI**，只读 /etc/dnsmasq.conf 与 conf-dir。
# 没有本适配器时，上面的写入会「成功但无效」——旁路网关场景下表现为
# 「客户端 DNS 没有被劫持到 OpenClash」，且没有任何报错。
#
# -----------------------------------------------------------------------------
# 设计原则：**只翻译 OpenClash 会写的那 6 个选项**，其余一律交给 Debian 自己的
# /etc/dnsmasq.conf 管理。盲目全量翻译会覆盖系统 DNS 策略，属于越界。
# 因此本文件产出的片段是「增量的、可删除的」：卸载时删掉该文件即完全回退。
# -----------------------------------------------------------------------------
# 用法：
#   dnsmasq-adapter.sh            # 生成/更新片段（幂等，内容不变则不落盘）
#   dnsmasq-adapter.sh --check    # 只校验前置条件，不写文件
#   dnsmasq-adapter.sh --print    # 打印将要写入的内容
#
# 环境变量：
#   OPENCLASH_RT_DNSMASQ_DIR   输出目录，默认 /etc/dnsmasq.d
#   OPENCLASH_RT_UCI           uci 可执行文件，默认自动探测 /sbin/uci
# =============================================================================
set -u

LOG_TAG="openclash-rt/dnsmasq-adapter"
OUT_DIR="${OPENCLASH_RT_DNSMASQ_DIR:-/etc/dnsmasq.d}"
OUT_FILE="$OUT_DIR/00-openclash-rt-uci.conf"

MODE="${1:-apply}"

log()  { printf '%s: %s\n' "$LOG_TAG" "$*" >&2; }
warn() { printf '%s: 警告: %s\n' "$LOG_TAG" "$*" >&2; }
die()  { printf '%s: %s\n' "$LOG_TAG" "$*" >&2; exit 1; }

# -----------------------------------------------------------------------------
# uci 探测
# -----------------------------------------------------------------------------
_uci() {
	if [ -n "${OPENCLASH_RT_UCI:-}" ]; then
		"$OPENCLASH_RT_UCI" "$@"
		return $?
	fi
	local p
	for p in /sbin/uci /usr/sbin/uci /usr/bin/uci; do
		if [ -x "$p" ]; then "$p" "$@"; return $?; fi
	done
	return 127
}

if ! _uci -q get openclash.config >/dev/null 2>&1; then
	# 没有 uci 或没有 openclash 配置，说明兼容层未就绪；静默退出不阻断任何流程
	log "uci 或 openclash 配置不可用，跳过"
	exit 0
fi

# -----------------------------------------------------------------------------
# 前置校验：Debian 的 dnsmasq 是否真的会加载 /etc/dnsmasq.d/*.conf
# -----------------------------------------------------------------------------
_check_conf_dir() {
	local rc=0
	if [ ! -f /etc/dnsmasq.conf ]; then
		warn "/etc/dnsmasq.conf 不存在——dnsmasq 可能未安装，翻译结果不会被加载"
		rc=1
	elif ! grep -qE '^[[:space:]]*conf-dir[[:space:]]*=[[:space:]]*/etc/dnsmasq\.d' /etc/dnsmasq.conf 2>/dev/null; then
		warn "/etc/dnsmasq.conf 未包含 conf-dir=/etc/dnsmasq.d —— 翻译结果不会被 dnsmasq 加载"
		warn "请添加：conf-dir=/etc/dnsmasq.d/,*.conf"
		rc=1
	fi
	return "$rc"
}

if [ "$MODE" = "--check" ]; then
	_check_conf_dir && log "前置条件满足" || log "前置条件不满足（见上方警告）"
	_uci -q get dhcp.@dnsmasq[0] >/dev/null 2>&1 \
		&& log "dhcp.@dnsmasq[0] 可寻址" \
		|| warn "dhcp.@dnsmasq[0] 不可寻址——请确认 /etc/config/dhcp 已安装"
	exit 0
fi

# -----------------------------------------------------------------------------
# 生成片段
# -----------------------------------------------------------------------------
_gen() {
	printf '# generated by openclash-rt - do not edit\n'
	printf '# 由 dhcp.@dnsmasq[0] 翻译而来；删除本文件即可完全回退到 Debian 原生配置。\n'
	printf '# 生成器: /usr/lib/openclash-rt/dnsmasq-adapter.sh\n'

	local got_any=0

	# --- server（列表）：上游用 add_list 追加，可能含 127.0.0.1#7874 这类带端口的写法
	#     dnsmasq 的语法与 OpenWrt 一致（# 分隔端口），可直接透传。
	local s
	s="$(_uci -q get dhcp.@dnsmasq[0].server 2>/dev/null)" || true
	if [ -n "$s" ]; then
		# uci get 对 list 返回空格分隔的多值
		local v
		for v in $s; do
			printf 'server=%s\n' "$v"
			got_any=1
		done
	fi

	# --- noresolv：1 表示不读 /etc/resolv.conf（只在 OpenClash 接管 DNS 时开启）
	local noresolv
	noresolv="$(_uci -q get dhcp.@dnsmasq[0].noresolv 2>/dev/null)" || true
	[ "$noresolv" = "1" ] && { printf 'no-resolv\n'; got_any=1; }

	# --- resolvfile → resolv-file
	local resolvfile
	resolvfile="$(_uci -q get dhcp.@dnsmasq[0].resolvfile 2>/dev/null)" || true
	[ -n "$resolvfile" ] && { printf 'resolv-file=%s\n' "$resolvfile"; got_any=1; }

	# --- localuse → local-service（只服务本地网段，OpenWrt 的 localuse 语义）
	local localuse
	localuse="$(_uci -q get dhcp.@dnsmasq[0].localuse 2>/dev/null)" || true
	[ "$localuse" = "1" ] && { printf 'local-service\n'; got_any=1; }

	# --- cachesize → cache-size
	local cachesize
	cachesize="$(_uci -q get dhcp.@dnsmasq[0].cachesize 2>/dev/null)" || true
	[ -n "$cachesize" ] && { printf 'cache-size=%s\n' "$cachesize"; got_any=1; }

	# --- filter_aaaa：只在为 1 时开启（0 是 dnsmasq 默认值，无需输出）
	local f6
	f6="$(_uci -q get dhcp.@dnsmasq[0].filter_aaaa 2>/dev/null)" || true
	[ "$f6" = "1" ] && { printf 'filter-aaaa\n'; got_any=1; }

	# 一个选项都没有时不要留下空片段影响排障
	#
	# ⚠️ 这里必须写成 if 语句而不是 `[ ... ] && printf`：
	#   `A && B` 的退出码是「短路后的结果」——条件为假时整体返回 1。
	#   若它恰好是函数体的最后一条命令，函数就会返回 1，调用方
	#   `if ! _gen >"$TMP"` 会误判为「生成失败」，进而删掉刚刚写好的
	#   临时文件并 die。实测症状正是：选项全都取到（got_any=1）时反而报
	#   「生成片段失败」，且片段文件不存在。
	if [ "$got_any" = "0" ]; then
		printf '# (当前 UCI 中无 OpenClash 托管的 dnsmasq 选项)\n'
	fi
}

# --print 直接输出，不落盘
if [ "$MODE" = "--print" ]; then
	_gen
	exit 0
fi

mkdir -p "$OUT_DIR" 2>/dev/null || die "无法创建 $OUT_DIR"

# 临时文件与目标**同目录**，有两个理由：
#   1) 不依赖 mktemp / TMPDIR —— TMPDIR 在受限环境里可能是 Windows 盘符路径
#      之类的非法值，会让 mktemp 产出不可用的路径；
#   2) 同一文件系统 → mv 是原子替换，dnsmasq 永远不会读到半截片段。
TMP="$OUT_DIR/.00-openclash-rt-uci.conf.tmp.$$"
trap 'rm -f "$TMP" 2>/dev/null' EXIT INT TERM

if ! _gen >"$TMP"; then
	rm -f "$TMP" 2>/dev/null
	die "生成片段失败"
fi

if [ -f "$OUT_FILE" ] && cmp -s "$TMP" "$OUT_FILE"; then
	rm -f "$TMP" 2>/dev/null
	log "内容无变化，跳过落盘"
	exit 0
fi

# 变更时留下旧版以便比对
[ -f "$OUT_FILE" ] && cp -f "$OUT_FILE" "$OUT_FILE.prev" 2>/dev/null || true

if mv -f "$TMP" "$OUT_FILE" 2>/dev/null; then
	chmod 0644 "$OUT_FILE" 2>/dev/null || true
	log "已更新 $OUT_FILE"
else
	cp -f "$TMP" "$OUT_FILE" || die "写入 $OUT_FILE 失败"
	chmod 0644 "$OUT_FILE" 2>/dev/null || true
	log "已更新 $OUT_FILE"
fi

_check_conf_dir || true
exit 0
